# Generated by Django 2.1.5 on 2019-01-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(help_text='Enter a food name:', max_length=200)),
                ('price', models.CharField(help_text='Enter a food price:', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(help_text='Enter a food type name:', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='typeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.FoodType'),
        ),
    ]
